# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from simpleeval import simple_eval
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 449)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.num1 = QtWidgets.QPushButton(self.centralwidget)
        self.num1.setGeometry(QtCore.QRect(20, 90, 91, 41))
        self.num1.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QPushButton(self.centralwidget)
        self.num2.setGeometry(QtCore.QRect(120, 90, 91, 41))
        self.num2.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num2.setObjectName("num2")
        self.num3 = QtWidgets.QPushButton(self.centralwidget)
        self.num3.setGeometry(QtCore.QRect(20, 140, 91, 41))
        self.num3.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num3.setObjectName("num3")
        self.num4 = QtWidgets.QPushButton(self.centralwidget)
        self.num4.setGeometry(QtCore.QRect(120, 140, 91, 41))
        self.num4.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num4.setObjectName("num4")
        self.num5 = QtWidgets.QPushButton(self.centralwidget)
        self.num5.setGeometry(QtCore.QRect(20, 190, 91, 41))
        self.num5.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num5.setObjectName("num5")
        self.num6 = QtWidgets.QPushButton(self.centralwidget)
        self.num6.setGeometry(QtCore.QRect(120, 190, 91, 41))
        self.num6.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num6.setObjectName("num6")
        self.num7 = QtWidgets.QPushButton(self.centralwidget)
        self.num7.setGeometry(QtCore.QRect(20, 240, 91, 41))
        self.num7.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num7.setObjectName("num7")
        self.num8 = QtWidgets.QPushButton(self.centralwidget)
        self.num8.setGeometry(QtCore.QRect(120, 240, 91, 41))
        self.num8.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num8.setObjectName("num8")
        self.num9 = QtWidgets.QPushButton(self.centralwidget)
        self.num9.setGeometry(QtCore.QRect(20, 290, 91, 41))
        self.num9.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num9.setObjectName("num9")
        self.num0 = QtWidgets.QPushButton(self.centralwidget)
        self.num0.setGeometry(QtCore.QRect(120, 290, 91, 41))
        self.num0.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.num0.setObjectName("num0")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(240, 160, 81, 41))
        self.divide.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.divide.setObjectName("divide")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(240, 110, 81, 41))
        self.multiply.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.multiply.setObjectName("multiply")
        self.smooth = QtWidgets.QPushButton(self.centralwidget)
        self.smooth.setGeometry(QtCore.QRect(240, 310, 81, 41))
        self.smooth.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.smooth.setObjectName("smooth")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(240, 260, 81, 41))
        self.minus.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.minus.setObjectName("minus")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(240, 210, 81, 41))
        self.plus.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.plus.setObjectName("plus")
        self.ce = QtWidgets.QPushButton(self.centralwidget)
        self.ce.setGeometry(QtCore.QRect(240, 60, 81, 41))
        self.ce.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.ce.setObjectName("ce")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(34, 189, 65);")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.label.setObjectName("label")
        self.leftbracket = QtWidgets.QPushButton(self.centralwidget)
        self.leftbracket.setGeometry(QtCore.QRect(140, 370, 51, 41))
        self.leftbracket.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.leftbracket.setObjectName("leftbracket")
        self.rightbracket = QtWidgets.QPushButton(self.centralwidget)
        self.rightbracket.setGeometry(QtCore.QRect(210, 370, 51, 41))
        self.rightbracket.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.rightbracket.setObjectName("rightbracket")
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(70, 370, 51, 41))
        self.dot.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.dot.setObjectName("dot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 342, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.onclicked()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.num1.setText(_translate("MainWindow", "1"))
        self.num2.setText(_translate("MainWindow", "2"))
        self.num3.setText(_translate("MainWindow", "3"))
        self.num4.setText(_translate("MainWindow", "4"))
        self.num5.setText(_translate("MainWindow", "5"))
        self.num6.setText(_translate("MainWindow", "6"))
        self.num7.setText(_translate("MainWindow", "7"))
        self.num8.setText(_translate("MainWindow", "8"))
        self.num9.setText(_translate("MainWindow", "9"))
        self.num0.setText(_translate("MainWindow", "0"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.smooth.setText(_translate("MainWindow", "="))
        self.minus.setText(_translate("MainWindow", "-"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.ce.setText(_translate("MainWindow", "CE"))
        self.label.setText(_translate("MainWindow", "0"))
        self.leftbracket.setText(_translate("MainWindow", "("))
        self.rightbracket.setText(_translate("MainWindow", ")"))
        self.dot.setText(_translate("MainWindow", "."))
    
    def writesymbol(self, num):
        if self.label.text().strip() == "0":
            self.label.setText(num)
        else:
            self.label.setText(self.label.text() + str(num))
            
    def deletesymbol(self):
        old_text = self.label.text()
        new_text = old_text[:-1]
        if new_text == "":
            new_text = "0"
        self.label.setText(new_text)

    def result(self):
        try:
            res:int|float = simple_eval(self.label.text())
            self.label.setText(str(res))
        except:
            res = "Error"
            self.label.setText(str(res))

    def onclicked(self):
        self.num0.clicked.connect(lambda: self.writesymbol(self.num0.text()))
        self.num1.clicked.connect(lambda: self.writesymbol(self.num1.text()))
        self.num2.clicked.connect(lambda: self.writesymbol(self.num2.text()))
        self.num3.clicked.connect(lambda: self.writesymbol(self.num3.text()))
        self.num4.clicked.connect(lambda: self.writesymbol(self.num4.text()))
        self.num5.clicked.connect(lambda: self.writesymbol(self.num5.text()))
        self.num6.clicked.connect(lambda: self.writesymbol(self.num6.text()))
        self.num7.clicked.connect(lambda: self.writesymbol(self.num7.text()))
        self.num8.clicked.connect(lambda: self.writesymbol(self.num8.text()))
        self.num9.clicked.connect(lambda: self.writesymbol(self.num9.text()))
        self.multiply.clicked.connect(lambda: self.writesymbol(self.multiply.text()))
        self.divide.clicked.connect(lambda: self.writesymbol(self.divide.text()))
        self.plus.clicked.connect(lambda: self.writesymbol(self.plus.text()))
        self.minus.clicked.connect(lambda: self.writesymbol(self.minus.text()))
        self.leftbracket.clicked.connect(lambda: self.writesymbol(self.leftbracket.text()))
        self.rightbracket.clicked.connect(lambda: self.writesymbol(self.rightbracket.text()))
        self.ce.clicked.connect(self.deletesymbol)
        self.smooth.clicked.connect(self.result)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
