name: Build PyQt App

on:
  push:
    tags:
      - "v*"
      - "V*"
  workflow_dispatch:

env:
  APP_NAME: calculator
  VERSION: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  # --- WINDOWS ---
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: python/gui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt pyinstaller
      - name: Build EXE
        run: pyinstaller --noconfirm --windowed --contents-directory "lib" main.py -n ${{ env.APP_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: python/gui/dist/*.exe

  # --- MACOS ---
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: python/gui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt pyinstaller
      - name: Build APP
        run: pyinstaller --onefile --windowed main.py -n ${{ env.APP_NAME }}
      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Installer" \
            "${{ env.APP_NAME }}-${{ env.VERSION }}.dmg" \
            "dist/${{ env.APP_NAME }}.app"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: python/gui/*.dmg

  # --- LINUX ---
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/gui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y binutils patchelf wget libfuse2
      - name: Install python deps
        run: pip install -r requirements.txt pyinstaller
      - name: Build binary
        run: pyinstaller --onefile --windowed main.py -n ${{ env.APP_NAME }}

      - name: Create DEB
        run: |
          mkdir -p deb/usr/bin
          mkdir -p deb/DEBIAN
          cp dist/${{ env.APP_NAME }} deb/usr/bin/${{ env.APP_NAME }}
          echo "Package: ${{ env.APP_NAME }}
          Version: 1.0.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Developer
          Description: App" > deb/DEBIAN/control
          dpkg-deb --build deb ${{ env.APP_NAME }}-${{ env.VERSION }}.deb

  # --- RELEASE ---
  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.exe
            artifacts/*.zip
            artifacts/*.dmg
            artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
