name: Build PyQt App

on:
  push:
    tags:
      - "v*-python"
  workflow_dispatch:

env:
  APP_NAME: calculator
  VERSION: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
# --- WINDOWS (Portable ZIP) ---
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: python/gui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt pyinstaller
      
      - name: Build Folder
        run: pyinstaller --noconfirm --windowed --contents-directory "lib" main.py -n ${{ env.APP_NAME }}
      
      - name: Create ZIP Archive
        shell: pwsh
        run: |
          Compress-Archive -Path dist\${{ env.APP_NAME }}\* -DestinationPath ..\..\${{ env.APP_NAME }}-win.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: ./*.zip

  # --- MACOS(.dmg) ---
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: python/gui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt pyinstaller
      - name: Build APP
        run: pyinstaller --onefile --windowed main.py -n ${{ env.APP_NAME }}
      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Installer" \
            "${{ env.APP_NAME }}-${{ env.VERSION }}.dmg" \
            "dist/${{ env.APP_NAME }}.app"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: python/gui/*.dmg

  # --- RELEASE ---
  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.zip
            artifacts/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
